# Generated by Django 5.0.1 on 2026-05-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, default='', help_text='ID of the affected resource', max_length=100),
        ),
    ]
