# Generated by Django 5.0.1 on 2026-05-29 22:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this threshold configuration', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Explanation of when to use this threshold')),
                ('attendance_threshold', models.FloatField(default=75.0, help_text='Minimum acceptable attendance rate (%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('grade_threshold', models.FloatField(default=10.0, help_text='Minimum acceptable average grade (0-20 scale)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('behavior_threshold', models.IntegerField(default=3, help_text='Maximum acceptable number of behavior incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('missed_appointments_threshold', models.IntegerField(default=2, help_text='Maximum acceptable number of missed appointments', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=False, help_text='Only one threshold can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_thresholds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(help_text='Unique student identifier', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('school_name', models.CharField(max_length=200)),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('region', models.CharField(help_text='Geographic region (e.g., Tunis, Sfax, Sousse)', max_length=100)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enrollment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('attendance_score', models.DecimalField(decimal_places=2, help_text='Attendance indicator (0-100)', max_digits=5)),
                ('academic_score', models.DecimalField(decimal_places=2, help_text='Academic performance indicator (0-100)', max_digits=5)),
                ('behavior_score', models.DecimalField(decimal_places=2, help_text='Behavior indicator (0-100)', max_digits=5)),
                ('overall_risk_score', models.DecimalField(decimal_places=2, help_text='Overall risk score (0-100)', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10)),
                ('explanation', models.TextField(help_text='Human-readable explanation of risk factors')),
                ('recommendations', models.TextField(help_text='Recommended interventions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='education.student')),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('goals', models.TextField(help_text='Specific, measurable goals')),
                ('actions', models.TextField(help_text='Concrete actions to be taken')),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('risk_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_plans', to='education.riskassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_plans', to='education.student')),
            ],
            options={
                'db_table': 'intervention_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.DecimalField(decimal_places=2, help_text='Grade out of 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('exam_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('PROJECT', 'Project')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='education.student')),
            ],
            options={
                'db_table': 'grade_records',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('MINOR', 'Minor Concern'), ('MODERATE', 'Moderate Concern'), ('SERIOUS', 'Serious Concern')], max_length=10)),
                ('category', models.CharField(choices=[('PARTICIPATION', 'Class Participation'), ('CONDUCT', 'Conduct'), ('SOCIAL', 'Social Interaction'), ('MOTIVATION', 'Motivation'), ('ATTENTION', 'Attention/Focus')], max_length=50)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_notes', to='education.student')),
            ],
            options={
                'db_table': 'behavior_notes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused Absence')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for absence or lateness', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='education.student')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_name', 'grade_level'], name='students_school__66d16b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['region'], name='students_region_5c098d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['student', 'assessment_date'], name='risk_assess_student_09f87e_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk_level'], name='risk_assess_risk_le_e2dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionplan',
            index=models.Index(fields=['student', 'status'], name='interventio_student_19d252_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionplan',
            index=models.Index(fields=['assigned_to'], name='interventio_assigne_90a8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['student', 'exam_date'], name='grade_recor_student_7c42b5_idx'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['subject'], name='grade_recor_subject_2ad7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviornote',
            index=models.Index(fields=['student', 'date'], name='behavior_no_student_48ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviornote',
            index=models.Index(fields=['severity'], name='behavior_no_severit_a9433b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance__student_6a013f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_5b1243_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
    ]
